import 'package:drift/drift.dart';

/// Board posts — short async messages between headmates.
///
/// Two audience flavours:
///   - `'public'`  — visible on the Public timeline and the target member's
///                   profile section.
///   - `'private'` — appears only in the Inbox of whoever is currently
///                   fronting as `target_member_id`.
///
/// `author_id` and `target_member_id` are plain TEXT refs — no foreign-key
/// constraints. The UI falls back to "Removed member" when the referenced
/// member no longer exists.
///
/// Sort field is `written_at DESC` so SP-imported posts appear at their
/// original SP timestamp, not the import date.
@DataClassName('MemberBoardPostRow')
class MemberBoardPosts extends Table {
  /// UUID primary key, generated by the creating device.
  TextColumn get id => text()();

  /// Recipient member; null for system-wide public posts
  /// (`audience = 'public'`, `target_member_id = null`).
  TextColumn get targetMemberId => text().nullable()();

  /// Writer; null only for legacy SP imports where SP `writtenBy` was unknown.
  TextColumn get authorId => text().nullable()();

  /// Audience enum — exactly `'public'` or `'private'`.
  /// Forward-compat default: any unrecognised value from a future-version
  /// peer is treated as `'public'` in the sync adapter (documented there).
  TextColumn get audience => text()();

  /// Optional post title.
  TextColumn get title => text().nullable()();

  /// Post body — required, non-empty (validated at the repository layer).
  TextColumn get body => text()();

  /// Immutable creation timestamp, set locally at insert.
  DateTimeColumn get createdAt => dateTime()();

  /// User-facing post timestamp. Equals `created_at` for native posts;
  /// equals SP `writtenAt` for SP imports.
  DateTimeColumn get writtenAt => dateTime()();

  /// Last-edited timestamp; null if the post has never been edited.
  DateTimeColumn get editedAt => dateTime().nullable()();

  /// Soft-delete tombstone. Never hard-delete; this field is always emitted
  /// in `_postFields` so the CRDT engine propagates tombstones correctly.
  BoolColumn get isDeleted => boolean().withDefault(const Constant(false))();

  @override
  String get tableName => 'member_board_posts';

  @override
  Set<Column> get primaryKey => {id};
}
