// Step-by-step migration tests (F28).
//
// Verifies each schema version transition individually by creating a database
// at version N, opening it through Drift (which triggers migration to current),
// and checking the expected schema changes were applied.
//
// This complements the per-version tests (migration_v38_test.dart) by also
// testing:
// - v38 -> v39 (terminology_use_english column)
// - Full upgrade path v30 -> v39 in a single database
//
// NOTE: Drift's SchemaVerifier/stepByStep API requires schema version dumps
// generated by `dart run drift_dev schema dump`. When those are set up, the
// tests below can be refactored to use the generated SchemaVerifier for
// stronger compile-time guarantees. For now, these tests use raw SQLite
// pragmas to verify schema state, matching the existing test pattern.
import 'dart:io';

import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sqlite3/sqlite3.dart' as raw;

import 'package:prism_plurality/core/database/app_database.dart';

void main() {
  group('migration v38 -> v39 (terminology_use_english)', () {
    test('fresh database has terminology_use_english column defaulting to 0',
        () async {
      final db = AppDatabase(NativeDatabase.memory());
      addTearDown(db.close);

      final colInfo = await db.customSelect(
        "SELECT name, dflt_value FROM pragma_table_info('system_settings') "
        "WHERE name = 'terminology_use_english'",
      ).get();

      expect(colInfo, hasLength(1));
      expect(colInfo.first.read<String>('name'), 'terminology_use_english');
      expect(colInfo.first.read<String>('dflt_value'), '0');
    });

    test('upgrade from v38 adds terminology_use_english column', () async {
      final tempDir =
          Directory.systemTemp.createTempSync('prism_migration_v39_');
      addTearDown(() {
        if (tempDir.existsSync()) {
          tempDir.deleteSync(recursive: true);
        }
      });

      final dbFile = File('${tempDir.path}/upgrade.db');

      // Create a raw database at schema version 38 with a minimal
      // system_settings table that includes gif_search_enabled (v38)
      // but lacks terminology_use_english (v39).
      final rawDb = raw.sqlite3.open(dbFile.path);
      try {
        rawDb.execute('PRAGMA user_version = 38;');
        rawDb.execute('''
          CREATE TABLE system_settings (
            id TEXT NOT NULL PRIMARY KEY DEFAULT 'singleton',
            system_name TEXT,
            show_quick_front INTEGER NOT NULL DEFAULT 1,
            accent_color_hex TEXT NOT NULL DEFAULT '#AF8EE9',
            per_member_accent_colors INTEGER NOT NULL DEFAULT 0,
            terminology INTEGER NOT NULL DEFAULT 0,
            custom_terminology TEXT,
            custom_plural_terminology TEXT,
            sharing_id TEXT,
            fronting_reminders_enabled INTEGER NOT NULL DEFAULT 0,
            fronting_reminder_interval_minutes INTEGER NOT NULL DEFAULT 60,
            theme_mode INTEGER NOT NULL DEFAULT 0,
            theme_brightness INTEGER NOT NULL DEFAULT 0,
            theme_style INTEGER NOT NULL DEFAULT 0,
            chat_enabled INTEGER NOT NULL DEFAULT 1,
            polls_enabled INTEGER NOT NULL DEFAULT 1,
            habits_enabled INTEGER NOT NULL DEFAULT 1,
            sleep_tracking_enabled INTEGER NOT NULL DEFAULT 1,
            quick_switch_threshold_seconds INTEGER NOT NULL DEFAULT 30,
            identity_generation INTEGER NOT NULL DEFAULT 0,
            chat_logs_front INTEGER NOT NULL DEFAULT 0,
            has_completed_onboarding INTEGER NOT NULL DEFAULT 0,
            sync_theme_enabled INTEGER NOT NULL DEFAULT 0,
            timing_mode INTEGER NOT NULL DEFAULT 0,
            habits_badge_enabled INTEGER NOT NULL DEFAULT 1,
            notes_enabled INTEGER NOT NULL DEFAULT 1,
            system_description TEXT,
            system_avatar_data BLOB,
            reminders_enabled INTEGER NOT NULL DEFAULT 1,
            font_scale REAL NOT NULL DEFAULT 1.0,
            font_family INTEGER NOT NULL DEFAULT 0,
            pin_lock_enabled INTEGER NOT NULL DEFAULT 0,
            biometric_lock_enabled INTEGER NOT NULL DEFAULT 0,
            auto_lock_delay_seconds INTEGER NOT NULL DEFAULT 0,
            display_font_in_app_bar INTEGER NOT NULL DEFAULT 1,
            is_deleted INTEGER NOT NULL DEFAULT 0,
            previous_accent_color_hex TEXT NOT NULL DEFAULT '',
            nav_bar_items TEXT NOT NULL DEFAULT '',
            nav_bar_overflow_items TEXT NOT NULL DEFAULT '',
            sync_navigation_enabled INTEGER NOT NULL DEFAULT 1,
            chat_badge_preferences TEXT NOT NULL DEFAULT '{}',
            gif_search_enabled INTEGER NOT NULL DEFAULT 1
          )
        ''');
        // Insert a row so we can verify the default value is applied
        rawDb.execute(
          "INSERT INTO system_settings (id) VALUES ('singleton')",
        );
      } finally {
        rawDb.close();
      }

      // Open through Drift — triggers v38 -> v39 migration.
      final db = AppDatabase(NativeDatabase(dbFile));
      addTearDown(db.close);

      // Verify column exists via pragma
      final colInfo = await db.customSelect(
        "SELECT name, dflt_value FROM pragma_table_info('system_settings') "
        "WHERE name = 'terminology_use_english'",
      ).get();

      expect(colInfo, hasLength(1));
      expect(colInfo.first.read<String>('dflt_value'), '0');

      // Verify existing row got the default value
      final rows = await db.customSelect(
        'SELECT terminology_use_english FROM system_settings',
      ).get();
      expect(rows, hasLength(1));
      expect(rows.first.read<int>('terminology_use_english'), 0);
    });
  });

  group('schema version consistency', () {
    test('fresh database and latest migration produce compatible schemas',
        () async {
      // Verify that a fresh database (via onCreate) has all expected
      // columns that migrations add. This catches drift between
      // the table definitions and the migration steps.
      final db = AppDatabase(NativeDatabase.memory());
      addTearDown(db.close);

      // All columns added by migrations v31-v39 should exist in fresh DB
      final settingsCols = await db.customSelect(
        "SELECT name FROM pragma_table_info('system_settings')",
      ).get();
      final colNames = settingsCols.map((r) => r.read<String>('name')).toSet();

      // v32
      expect(colNames, contains('display_font_in_app_bar'));
      // v34
      expect(colNames, contains('sharing_id'));
      // v35
      expect(colNames, contains('identity_generation'));
      // v38
      expect(colNames, contains('gif_search_enabled'));
      // v39
      expect(colNames, contains('terminology_use_english'));

      // v34: sharing_requests table should exist
      final srTable = await db.customSelect(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'sharing_requests'",
      ).get();
      expect(srTable, hasLength(1));

      // v36: media_attachments table should exist
      final maTable = await db.customSelect(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'media_attachments'",
      ).get();
      expect(maTable, hasLength(1));
    });

    test('schemaVersion matches the highest migration step', () {
      // If someone adds a new migration step but forgets to bump
      // schemaVersion, this test will catch it.
      final db = AppDatabase(NativeDatabase.memory());
      addTearDown(db.close);

      // Current schema version should be 44. Update this when adding
      // new migrations to ensure the version is bumped.
      expect(db.schemaVersion, 44);
    });
  });
}
