import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:prism_plurality/core/database/database_encryption.dart';
import 'package:sqlite3/sqlite3.dart' as raw;

const _legacyWindowsCompanyDir = 'com.prismplural';
const _legacyWindowsProductDir = 'prism_plurality';
const _windowsMigrationMarker = '.prism_windows_app_data_migrated_v1';
const _windowsLegacyMigratedMarker =
    '.prism_windows_app_data_migrated_to_prism_v1';
const _windowsLegacyMigrationStagingDir =
    'prism_plurality.migration-in-progress';

typedef WindowsCurrentDataProbe = Future<bool> Function(Directory currentDir);
typedef WindowsMigrationVerifier = Future<void> Function(Directory restoredDir);
typedef DirectoryCopier =
    Future<void> Function(Directory source, Directory destination);

/// Returns the directory the app should store its persistent data in.
///
/// On iOS / macOS / Android, `getApplicationDocumentsDirectory()` is a
/// sandboxed per-app path, which is the right place for the Drift and sync
/// databases.
///
/// On Linux and Windows, `getApplicationDocumentsDirectory()` returns the
/// user's shared `~/Documents` folder — dropping sqlite files there would
/// clutter the user's personal Documents and confuse file managers, cloud-sync
/// tools, and backup software. Use the XDG data dir instead
/// (`~/.local/share/<app>/` on Linux).
Future<Directory> getAppDataDir() {
  if (Platform.isWindows) {
    return _getMigratedWindowsAppDataDir();
  }
  if (Platform.isLinux) {
    return getApplicationSupportDirectory();
  }
  return getApplicationDocumentsDirectory();
}

Future<Directory> _getMigratedWindowsAppDataDir() async {
  final dir = await getApplicationSupportDirectory();
  await migrateWindowsLegacyAppSupportDirIfNeeded(currentDir: dir);
  return dir;
}

@visibleForTesting
class WindowsAppSupportMigrationResult {
  const WindowsAppSupportMigrationResult._({
    required this.migrated,
    required this.reason,
    this.backupPath,
  });

  const WindowsAppSupportMigrationResult.migrated({String? backupPath})
    : this._(migrated: true, reason: 'migrated', backupPath: backupPath);

  const WindowsAppSupportMigrationResult.skipped(String reason)
    : this._(migrated: false, reason: reason);

  final bool migrated;
  final String reason;
  final String? backupPath;

  bool get shouldBlockStartup => switch (reason) {
    'legacy-in-use' || 'migration-failed' || 'current-has-user-data' => true,
    _ => false,
  };
}

/// Migrates Windows data from the app-support path generated by the old native
/// metadata (`com.prismplural\prism_plurality`) to the branded metadata path
/// (`Prism Plural\Prism`).
///
/// Flutter's Windows path provider derives application support paths from the
/// EXE VERSIONINFO `CompanyName` and `ProductName` fields. Changing those fields
/// for user-facing branding moved Prism's database, secure-storage file, and
/// shared preferences unless we explicitly bring the old directory forward.
Future<WindowsAppSupportMigrationResult>
migrateWindowsLegacyAppSupportDirIfNeeded({
  Directory? currentDir,
  Directory? legacyDir,
  DateTime Function()? now,
  WindowsCurrentDataProbe? currentHasUserData,
  WindowsMigrationVerifier? verifyRestoredData,
  DirectoryCopier? copyDirectory,
}) async {
  if (!Platform.isWindows && (currentDir == null || legacyDir == null)) {
    return const WindowsAppSupportMigrationResult.skipped('not-windows');
  }

  currentDir ??= await getApplicationSupportDirectory();
  legacyDir ??= _legacyWindowsAppSupportDirFor(currentDir);
  final legacyStagingDir = _legacyWindowsMigrationStagingDirFor(legacyDir);

  final currentPath = p.normalize(p.absolute(currentDir.path));
  final legacyPath = p.normalize(p.absolute(legacyDir.path));
  if (p.equals(currentPath, legacyPath)) {
    return const WindowsAppSupportMigrationResult.skipped('same-directory');
  }

  final currentMarker = File(p.join(currentDir.path, _windowsMigrationMarker));
  if (await currentMarker.exists()) {
    return const WindowsAppSupportMigrationResult.skipped('already-migrated');
  }

  var legacySourceDir = legacyDir;
  if (!await legacySourceDir.exists() && await legacyStagingDir.exists()) {
    legacySourceDir = legacyStagingDir;
  }

  final legacyMarker = File(
    p.join(legacySourceDir.path, _windowsLegacyMigratedMarker),
  );
  if (await legacyMarker.exists()) {
    return const WindowsAppSupportMigrationResult.skipped(
      'legacy-already-migrated',
    );
  }

  if (!await _directoryContainsPrismData(legacySourceDir)) {
    return const WindowsAppSupportMigrationResult.skipped('no-legacy-data');
  }

  final currentExists = await currentDir.exists();
  if (currentExists &&
      !await _isDirectoryEmpty(currentDir) &&
      await (currentHasUserData ?? _currentDirectoryHasUserData)(currentDir)) {
    return const WindowsAppSupportMigrationResult.skipped(
      'current-has-user-data',
    );
  }

  final stagedLegacyDir = await _stageLegacyDirectoryForMigration(
    legacyDir: legacyDir,
    sourceDir: legacySourceDir,
    stagingDir: legacyStagingDir,
  );
  if (stagedLegacyDir == null) {
    return const WindowsAppSupportMigrationResult.skipped('legacy-in-use');
  }

  Directory? backupDir;
  if (currentExists && !await _isDirectoryEmpty(currentDir)) {
    backupDir = await _uniqueSiblingDirectory(
      currentDir,
      '${p.basename(currentDir.path)}.before-legacy-migration',
      now: now,
    );
    await backupDir.parent.create(recursive: true);
    await currentDir.rename(backupDir.path);
  } else if (currentExists) {
    await currentDir.delete(recursive: true);
  }

  try {
    await (copyDirectory ?? _copyDirectory)(stagedLegacyDir, currentDir);
    await (verifyRestoredData ?? _verifyRestoredWindowsData)(currentDir);
    await currentMarker.writeAsString(
      'Migrated from $legacyPath\n'
      'Backup of previous current directory: ${backupDir?.path ?? '<none>'}\n',
      flush: true,
    );
    await File(
      p.join(stagedLegacyDir.path, _windowsLegacyMigratedMarker),
    ).writeAsString('Migrated to $currentPath\n', flush: true);
  } catch (e) {
    if (await currentDir.exists()) {
      await currentDir.delete(recursive: true);
    }
    if (backupDir != null && await backupDir.exists()) {
      await backupDir.rename(currentDir.path);
    }
    debugPrint('[APP_DATA] Windows legacy app-data migration failed: $e');
    return const WindowsAppSupportMigrationResult.skipped('migration-failed');
  } finally {
    try {
      await _restoreStagedLegacyDirectory(
        legacyDir: legacyDir,
        stagingDir: stagedLegacyDir,
        now: now,
      );
    } catch (e) {
      debugPrint('[APP_DATA] Failed to restore staged legacy directory: $e');
    }
  }

  return WindowsAppSupportMigrationResult.migrated(backupPath: backupDir?.path);
}

Directory _legacyWindowsAppSupportDirFor(Directory currentDir) {
  final appDataRoot = currentDir.parent.parent;
  return Directory(
    p.join(
      appDataRoot.path,
      _legacyWindowsCompanyDir,
      _legacyWindowsProductDir,
    ),
  );
}

Directory _legacyWindowsMigrationStagingDirFor(Directory legacyDir) {
  return Directory(
    p.join(legacyDir.parent.path, _windowsLegacyMigrationStagingDir),
  );
}

Future<Directory?> _stageLegacyDirectoryForMigration({
  required Directory legacyDir,
  required Directory sourceDir,
  required Directory stagingDir,
}) async {
  if (p.equals(
    p.normalize(p.absolute(sourceDir.path)),
    p.normalize(p.absolute(stagingDir.path)),
  )) {
    return stagingDir;
  }
  if (await stagingDir.exists()) return null;
  try {
    return await legacyDir.rename(stagingDir.path);
  } on FileSystemException {
    // A still-running old Prism process can keep SQLite files open in the
    // legacy support directory. If Windows refuses the rename, skip migration
    // for this launch instead of copying a live WAL/DB set.
    return null;
  }
}

Future<void> _restoreStagedLegacyDirectory({
  required Directory legacyDir,
  required Directory stagingDir,
  DateTime Function()? now,
}) async {
  if (!await stagingDir.exists()) return;
  if (!await legacyDir.exists()) {
    await stagingDir.rename(legacyDir.path);
    return;
  }

  final preserved = await _uniqueSiblingDirectory(
    legacyDir,
    '${p.basename(legacyDir.path)}.migration-source',
    now: now,
  );
  await stagingDir.rename(preserved.path);
}

Future<bool> _directoryContainsPrismData(Directory dir) async {
  if (!await dir.exists()) return false;
  const names = {
    'prism.db',
    'prism.db-wal',
    'prism.db-shm',
    'prism_sync.db',
    'prism_sync.db-wal',
    'prism_sync.db-shm',
    'flutter_secure_storage.dat',
    'shared_preferences.json',
    'crypto_boot_log.json',
    'fronting_migration_breadcrumbs.json',
    'prism_media',
  };
  await for (final entity in dir.list(followLinks: false)) {
    if (names.contains(p.basename(entity.path))) return true;
  }
  return false;
}

Future<bool> _currentDirectoryHasUserData(Directory currentDir) async {
  final dbFile = File(p.join(currentDir.path, 'prism.db'));
  if (!await dbFile.exists()) return false;

  final key = await readDatabaseKeyHex();
  if (key == null) return true;

  try {
    final hasUserData =
        await _encryptedDatabaseHasRows(dbFile.path, key, const [
          'members',
          'fronting_sessions',
          'conversations',
          'chat_messages',
          'polls',
          'poll_options',
          'poll_votes',
          'sleep_sessions',
          'habits',
          'habit_completions',
          'member_groups',
          'member_group_entries',
          'pk_group_sync_aliases',
          'pk_group_entry_deferred_sync_ops',
          'custom_fields',
          'custom_field_values',
          'notes',
          'member_board_posts',
          'front_session_comments',
          'conversation_categories',
          'reminders',
          'friends',
          'sharing_requests',
          'media_attachments',
          'sp_sync_state',
          'sp_id_map',
          'pk_mapping_state',
        ]);
    return hasUserData;
  } catch (_) {
    return true;
  }
}

Future<bool> _encryptedDatabaseHasRows(
  String dbPath,
  String hexKey,
  List<String> tables,
) async {
  final db = raw.sqlite3.open(dbPath);
  try {
    configurePrismSqliteConnection(db, hexKey: hexKey);
    db.select('SELECT count(*) FROM sqlite_master;');
    for (final table in tables) {
      final exists = db.select(
        'SELECT 1 FROM sqlite_master WHERE type = ? AND name = ? LIMIT 1',
        ['table', table],
      );
      if (exists.isEmpty) continue;
      final rows = db.select('SELECT 1 FROM "$table" LIMIT 1');
      if (rows.isNotEmpty) return true;
    }
    return false;
  } finally {
    db.close();
  }
}

Future<void> _verifyRestoredWindowsData(Directory restoredDir) async {
  final dbPath = p.join(restoredDir.path, 'prism.db');
  if (!await File(dbPath).exists()) return;

  final key = await readDatabaseKeyHex();
  if (key == null || !tryOpenEncryptedDb(dbPath, key)) {
    throw StateError('Migrated Windows app database could not be opened.');
  }
}

Future<bool> _isDirectoryEmpty(Directory dir) async {
  await for (final _ in dir.list(followLinks: false)) {
    return false;
  }
  return true;
}

Future<Directory> _uniqueSiblingDirectory(
  Directory dir,
  String basename, {
  DateTime Function()? now,
}) async {
  final stamp = ((now ?? DateTime.now)()).toUtc().toIso8601String().replaceAll(
    RegExp(r'[:.]'),
    '-',
  );
  var candidate = Directory(p.join(dir.parent.path, '$basename.$stamp'));
  var index = 1;
  while (await candidate.exists()) {
    candidate = Directory(p.join(dir.parent.path, '$basename.$stamp.$index'));
    index += 1;
  }
  return candidate;
}

Future<void> _copyDirectory(Directory source, Directory destination) async {
  await destination.create(recursive: true);
  await for (final entity in source.list(
    recursive: false,
    followLinks: false,
  )) {
    final name = p.basename(entity.path);
    final targetPath = p.join(destination.path, name);
    if (entity is Directory) {
      await _copyDirectory(entity, Directory(targetPath));
    } else if (entity is File) {
      await entity.copy(targetPath);
    }
  }
}
